name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    uses: gorfednet/.github/.github/workflows/pr-check-vite-spa.yml@main

  browser-compat:
    if: github.event_name == 'pull_request'
    uses: gorfednet/.github/.github/workflows/browser-compat.yml@main
